first test to make sure the functions work as written in script form to get an evaporation profile

In [6]:
import os
notebook_wd = os.getcwd()

In [23]:
os.chdir(os.path.join(notebook_wd, '..'))
from src.d00_utils.conf_utils import *
from src.d00_utils.calc_utils import *
from src.d00_utils.flux_utils import *
from src.d03_modeling.numerical_model import differentiate

In [8]:
cmpds, water = load_compounds()
cmpds

{'triethylene_glycol': {'name': 'PEG-3',
  'D_g': 5.95e-06,
  'mw': 0.1502,
  'rho': 1108.0,
  'c_inf': 0,
  'vp': 0.0668,
  'T_vp': 298,
  'dH': 78300.0},
 'hexaethylene_glycol': {'name': 'PEG-6',
  'D_g': 4.26e-06,
  'mw': 0.2823,
  'rho': 1180.0,
  'c_inf': 0,
  'vp': 3.05e-05,
  'T_vp': 298,
  'dH': 102100.0}}

In [10]:
params = load_parameters()
params

{'r_init': 5e-05,
 'X_h2o': 0.7,
 'composition': {'triethylene_glycol': 0.1, 'hexaethylene_glycol': 0.1}}

In [15]:
x_cmpds = convert_molar_abundances_to_mole_fractions(params['composition'], x_water=params['X_h2o'])
v_init = convert_radius_to_volume(params['r_init'])
n_inits = convert_volume_to_moles(v_init, cmpds, water, x_cmpds, x_water=params['X_h2o'])
n_inits

array([1.05540888e-09, 1.05540888e-09])

In [21]:
gp_dict = pack_partition_dict(cmpds, water, T=298, x_water=params['X_h2o'])

In [34]:
ns = differentiate(function=gas_particle_partition, function_params_dict=gp_dict, n_inits=n_inits, step_count=100, step=1)

In [75]:
n_waters = convert_water_mole_fraction_to_moles(ns, x_water=params['X_h2o'])
n_totals = np.concatenate((ns, n_waters.reshape(len(n_waters), 1)), 
                          axis=1)  # add water ns to n_total

wet_cmpds = {**cmpds, **{'water': water}}

Vs = np.empty(len(ns))
rs = np.empty(len(ns))
for tick in range(len(n_wets)):
    Vs[tick] = convert_moles_to_volume(wet_cmpds, n_totals[tick])
    rs[tick] = convert_volume_to_radius(Vs[tick])
    
rs

array([5.00000000e-05, 4.99992506e-05, 4.99985013e-05, 4.99977520e-05,
       4.99970027e-05, 4.99962535e-05, 4.99955043e-05, 4.99947551e-05,
       4.99940060e-05, 4.99932569e-05, 4.99925078e-05, 4.99917588e-05,
       4.99910098e-05, 4.99902608e-05, 4.99895118e-05, 4.99887629e-05,
       4.99880141e-05, 4.99872652e-05, 4.99865164e-05, 4.99857676e-05,
       4.99850189e-05, 4.99842702e-05, 4.99835215e-05, 4.99827729e-05,
       4.99820243e-05, 4.99812757e-05, 4.99805272e-05, 4.99797786e-05,
       4.99790302e-05, 4.99782817e-05, 4.99775333e-05, 4.99767849e-05,
       4.99760366e-05, 4.99752883e-05, 4.99745400e-05, 4.99737918e-05,
       4.99730436e-05, 4.99722954e-05, 4.99715472e-05, 4.99707991e-05,
       4.99700510e-05, 4.99693030e-05, 4.99685550e-05, 4.99678070e-05,
       4.99670591e-05, 4.99663112e-05, 4.99655633e-05, 4.99648154e-05,
       4.99640676e-05, 4.99633198e-05, 4.99625721e-05, 4.99618244e-05,
       4.99610767e-05, 4.99603291e-05, 4.99595814e-05, 4.99588339e-05,
      

In [86]:
np.linspace(0, 5*4, 4+1, endpoint=True)

array([ 0.,  5., 10., 15., 20.])

In [87]:
Vs

array([5.23598776e-13, 5.23575234e-13, 5.23551694e-13, 5.23528156e-13,
       5.23504619e-13, 5.23481084e-13, 5.23457551e-13, 5.23434020e-13,
       5.23410490e-13, 5.23386962e-13, 5.23363436e-13, 5.23339912e-13,
       5.23316389e-13, 5.23292869e-13, 5.23269350e-13, 5.23245832e-13,
       5.23222317e-13, 5.23198803e-13, 5.23175291e-13, 5.23151780e-13,
       5.23128272e-13, 5.23104765e-13, 5.23081260e-13, 5.23057756e-13,
       5.23034254e-13, 5.23010755e-13, 5.22987256e-13, 5.22963760e-13,
       5.22940265e-13, 5.22916772e-13, 5.22893281e-13, 5.22869792e-13,
       5.22846304e-13, 5.22822818e-13, 5.22799334e-13, 5.22775851e-13,
       5.22752370e-13, 5.22728891e-13, 5.22705414e-13, 5.22681939e-13,
       5.22658465e-13, 5.22634993e-13, 5.22611523e-13, 5.22588054e-13,
       5.22564587e-13, 5.22541122e-13, 5.22517659e-13, 5.22494197e-13,
       5.22470738e-13, 5.22447280e-13, 5.22423823e-13, 5.22400369e-13,
       5.22376916e-13, 5.22353465e-13, 5.22330015e-13, 5.22306568e-13,
      